folio-org/edge-caiasoft

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

[EDGCSOFT-8](https://issues.folio.org/browse/EDGCSOFT-8) - EDGCSOFT (edge-caiasoft) pre-release - v0.1.0
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGCSOFT-8 - update NEWS, edge-common-spring v.1.0.0

---

src/main/java/org/folio/ed/security/CaiaSoftSecureStoreFactory.java
src/main/java/org/folio/ed/service/CaiaSoftSecurityManagerService.java
src/test/java/org/folio/ed/TestSuite.java
src/test/java/org/folio/ed/security/CaiaSoftSecureStoreFactoryTest.java

[EDGCSOFT-13](https://issues.folio.org/browse/EDGCSOFT-13)- Deployment with aws params for credentials produces exception
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …

EDGCSOFT-13 - Deployment with aws params for credentials produces exception

---

NEWS.md
README.md
descriptors/ModuleDescriptor-template.json
pom.xml
src/test/java/org/folio/ed/service/RemoteStorageServiceTest.java

[EDGCSOFT-3](https://issues.folio.org/browse/EDGCSOFT-3) - EDGCSOFT (edge-caiasoft) release …

EDGCSOFT-3  - EDGCSOFT (edge-caiasoft) release

---

README.md
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/main/java/org/folio/ed/service/CaiaSoftSecurityManagerService.java
src/main/resources/application.yml
src/test/java/org/folio/ed/controller/AccessionControllerTest.java
src/test/java/org/folio/ed/controller/ReturnControllerTest.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java
src/test/java/org/folio/ed/service/RemoteStorageServiceTest.java

[EDGCSOFT-10](https://issues.folio.org/browse/EDGCSOFT-10) - Improvement: Making system user configurable
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGCSOFT-10 - Improvement: Making system user configurable

---

README.md

Recently had to deploy this onto rancher and wanted to document all the steps that were necessary.

FOLIO-3293: Adding rancher deployment instructions to readme

---

pom.xml

[EDGCSOFT-19](https://issues.folio.org/browse/EDGCSOFT-19) - Kiwi R3 2021 - Log4j vulnerability verification and correction

EDGCSOFT-19 - Kiwi R3 2021 - Log4j vulnerability verification and correction

---

NEWS.md
pom.xml

[EDGCSOFT-23](https://issues.folio.org/browse/EDGCSOFT-23) - EDGCSOFT (edge-caiasoft) Kiwi Bugfix release

EDGECSOFT-23 - Release 1.1.1

---

NEWS.md
pom.xml

[EDGCSOFT-22](https://issues.folio.org/browse/EDGCSOFT-22) - EDGCSOFT (edge-caiasoft) Juniper Hotfix release

EDGCSOFT-22 - Release 1.0.1

---

pom.xml

[EDGCSOFT-24](https://issues.folio.org/browse/EDGCSOFT-24) - Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade

EDGCSOFT-24 - Kiwi R3 2021 - Log4j edge- modules 2.17.0 upgrade

---

NEWS.md
pom.xml

[EDGCSOFT-25](https://issues.folio.org/browse/EDGCSOFT-25) - Kiwi R3 2021 Log4j module release

EDGCSOFT-25 - Release 1.1.2

---

NEWS.md
pom.xml

[EDGCSOFT-27](https://issues.folio.org/browse/EDGCSOFT-27) - Juniper R2 2021 Log4j module release

EDGCSOFT-27 - Release 1.0.2

---

pom.xml
src/main/java/org/folio/ed/configuration/EdgeCaiaSoftSpringConfiguration.java
src/main/java/org/folio/ed/service/CaiaSoftIntegrationService.java
src/main/resources/application.yml

[EDGCSOFT-17](https://issues.folio.org/browse/EDGCSOFT-17) - edge-caiasoft: folio-spring-base v3 update
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGCSOFT-17 - edge-caiasoft: folio-spring-base v3 update

---

NEWS.md
pom.xml

[EDGCSOFT-28](https://issues.folio.org/browse/EDGCSOFT-28) - Release 1.2.0

EDGCSOFT-28 - Release 1.2.0

---

pom.xml

[EDGCSOFT-36](https://issues.folio.org/browse/EDGCSOFT-36) - Spring4Shell Lotus R1 2022 (CVE-2022-22965)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

EDGCSOFT-36 - spring-boot-starter-parent v.2.6.6

---

NEWS.md
pom.xml

[EDGCSOFT-38](https://issues.folio.org/browse/EDGCSOFT-38) - EDGCSOFT (edge-caiasoft) Lotus BF release
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …

EDGCSOFT-38 - Release 1.2.1

---

pom.xml

Jira: https://issues.folio.org/browse/EDGCSOFT-33
folio-spring-base update to 4.1.0

EDGCSOFT-33: folio-spring-base update

---

pom.xml

Jira: https://issues.folio.org/browse/EDGCSOFT-39
Update the Spring Boot to 2.7.0

EDGCSOFT-39: Spring Boot 2.7 for Morning Glory R2 2022

---

pom.xml

[EDGCSOFT-42](https://issues.folio.org/browse/EDGCSOFT-42) - Clean-up maven duplicate dependencies to the FOLIO libraries
Clean-up maven duplicate dependencies to the FOLIO libraries.
Review pom.xml, update versions, remove duplicate dependency to the folio-spring-base library.
Ideally all of the PRs involved in breaking changes would be merged in the same …

EDGCSOFT-42 - Clean-up maven duplicate dependencies to the FOLIO libraries

---

pom.xml

https://dev.folio.org/guidelines/release-procedures/

set next dev version to 1.4.0-SNAPSHOT

---

NEWS.md
pom.xml

[EDGCSOFT-32](https://issues.folio.org/browse/EDGCSOFT-32) - Release 1.3.0

EDGCSOFT-32 - Release 1.3.0

---

pom.xml

[EDGCSOFT-44](https://issues.folio.org/browse/EDGCSOFT-44) - Update to a new version of edge common spring
Update edge-common-spring to version 2.0.2
edge-common-spring version updated
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …

EDGCSOFT-44 - Update to a new version of edge common spring

---

NEWS.md
pom.xml

[EDGCSOFT-43](https://issues.folio.org/browse/EDGCSOFT-43) - EDGCSOFT (edge-caiasoft) MG Bugfix release

EDGCSOFT-43 - Release 1.3.1

---

NEWS.md
pom.xml

[EDGCSOFT-40](https://issues.folio.org/browse/EDGCSOFT-40) - EDGCSOFT (edge-caiasoft) Nolana release

EDGCSOFT-40 - Release 1.4.0

---

PULL_REQUEST_TEMPLATE.md
src/main/resources/application.yml

[EDGCSOFT-46](https://issues.folio.org/browse/EDGCSOFT-46)
Logging improvement - Configuration
1. Enable the /loggers endpoint in application.yml file
3. "Check logging" added to PULL_REQUEST_TEMPLATE.md

[EDGCSOFT-46]: Logging improvement - Configuration

---

.rancher-pipeline.yml
Dockerfile
Jenkinsfile
pom.xml
src/main/java/org/folio/ed/controller/ReturnController.java
src/main/java/org/folio/ed/error/DefaultErrorHandler.java
src/main/java/org/folio/ed/service/CaiaSoftIntegrationService.java
src/main/java/org/folio/ed/service/CaiaSoftSecurityManagerService.java
src/main/java/org/folio/ed/util/ConfigurationHelpers.java
src/main/resources/application.yml
src/test/java/org/folio/ed/TestBase.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java

[EDGCSOFT-47](https://issues.folio.org/browse/EDGCSOFT-47): Update to Java 17
[EDGCSOFT-48](https://issues.folio.org/browse/EDGCSOFT-48): Update the module to Spring boot v3.0.0 and identify issues
[Migrating to Spring Boot v3.0.0](https://wiki.folio.org/display/FOLIJET/Migration+to+Spring+Boot+v3.0.0+How+to)
Ideally all of the PRs involved in breaking …

EDGCSOFT-47/48: Update to Java 17/ Update the module to Spring boot v3.0.0 and identify issues

---

src/main/java/org/folio/ed/error/DefaultErrorHandler.java
src/main/java/org/folio/ed/handler/RetrievalQueueRecordHandler.java
src/main/java/org/folio/ed/security/CaiaSoftSecureStoreFactory.java
src/main/java/org/folio/ed/security/SecureTenantsProducer.java
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/main/java/org/folio/ed/service/CaiaSoftIntegrationService.java
src/main/java/org/folio/ed/service/CaiaSoftSecurityManagerService.java
src/main/java/org/folio/ed/service/RemoteStorageService.java

EDGCSOFT-34 (https://issues.folio.org/browse/EDGCSOFT-34) 
Adding loggers as part of logging improvements
_By following the practices mentioned in https://wiki.folio.org/display/DD/Logging,
Added loggers wherever needed._
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …

EDGCSOFT-34 Logging improvement

---

pom.xml

The purpose of the PR is to update the edge common spring version so that we get the folio spring base version of 7.0.0
**Evidence :**
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

EDGCSOFT-50 - Updating edge common spring version to get the folio spring base version 7.0.0

---

src/main/java/org/folio/ed/handler/RetrievalQueueRecordHandler.java
src/main/java/org/folio/ed/service/CaiaSoftIntegrationService.java
src/main/resources/application.yml
src/test/java/org/folio/ed/handler/RetrievalQueueRecordHandlerTest.java

[EDGCSOFT-53](https://issues.folio.org/browse/EDGCSOFT-53) : Implement RTR for edge-caiasoft
This module has a direct dependency on authn/login. We need to replace that dependency with new shared code in edge-common-spring.
integrated edge-common-spring library, which internally uses folio-spring-system-user library from folio-spring-support

EDGCSOFT-53 : Implement RTR in edge-caiasoft

---

pom.xml

Migrate to folio-spring-support 7.2.x and Spring Boot 3.1.X
Upgrade the versions in pom.xml …

EDGCSOFT-56 - Migrate to folio-spring-support 7.2.x and Spring Boot 3.1.X

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Poppy release
While it's helpful for reviewers to help identify potential problems, ensuring …

EDGCSOFT-55 - Poppy release

---

pom.xml
src/main/resources/application.yml

The purpose is to update the versions for Q release.
While it's helpful for reviewers to …

EDGCSOFT-59 - Update pom versions.

---

NEWS.md
pom.xml

For Q release.
While it's helpful for reviewers to help identify potential problems, …

EDGCSOFT-61 - Release 2.2.0

---

NEWS.md
pom.xml

To release 2.2.1

---

NEWS.md
pom.xml
src/main/java/org/folio/ed/EdgeCaiaSoftApplication.java

To release 2.2.2

---

pom.xml

EDGCSOFT-67 - post release 2.2.2

---

NEWS.md
pom.xml

Release 2.2.3
While it's helpful for reviewers to help identify potential problems, ensuring …

To release 2.2.3

---

NEWS.md
pom.xml

To release 2.2.4
While it's helpful for reviewers to help identify potential problems, …

To release 2.2.4

---

NEWS.md
pom.xml

Ramsons release

---

pom.xml

fix tls initialization

---

NEWS.md
pom.xml

To release 2.3.2

---

.dockerignore
.rancher-pipeline.yml
Dockerfile
Jenkinsfile
NEWS.md
pom.xml

FOLIO-4228 - Upgrade spring and java versions

---

pom.xml
src/main/java/org/folio/ed/security/TenantAwareAWSParamStore.java
src/test/java/org/folio/ed/security/TenantAwareAWSParamStoreTest.java

[EDGCSOFT-77](https://folio-org.atlassian.net/browse/EDGCSOFT-77)

EDGCSOFT-77 Sunflower 2025 R1 - Migrate AWS SDK for Java from 1.x to 2.x

---

NEWS.md
pom.xml

[EDGCSOFT-81](https://folio-org.atlassian.net/browse/EDGCSOFT-81)

EDGCSOFT-81 Sunflower R1 2025 release

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
CODEOWNERS

- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- for codeowners been automatically tagged in PRs
- add `dependabot.yml` config file
- add `PULL_REQUEST_TEMPLATE.md` file
- add `CODEOWNERS` file
[EDGCSOFT-82](https://folio-org.atlassian.net/browse/EDGCSOFT-82) …

EDGCSOFT-82: Add config file for dependabot, code owners and template for pull request
